### ISSUE TITLE
Assembly hierarchy before rendering

### ISSUE THREAD

**Issue by fragmuffin** [cqparts/cqparts_webapi#2]
When browsing models, it could be good to be able to select a sub-assembly before the whole model is rendered.

Example use-case: `/cqparts/export/showcase/Rover`
![image](https://user-images.githubusercontent.com/2626190/44850007-3c861d80-ac9f-11e8-8e9d-0c2024ebbf67.png)

That [awesome] buggy takes some time to generate, but you may just want to go directly to the front left wheel bracket so you can export it to print it (potentially fully automated).

That doesn't mean the rest of it needs rendering.

**REST API**
The answer to this would be in an implementation of a REST API (which is what `flask` is better known for implementing), one method to list _components_, another to list that _component's_ hierarchy, and another to GET models for _sub-components_

I'm just typing out loud here, I don't fully know what `cqparts_webapi` will be used for yet, but there's so much potential!
Perhaps we could set up a server once it's stable and caching.

**Comment by zignig** [comment]
The funny thing is this is about 2/3rds of the cqparts_bucket,  the rest does not have a clean export.

**Comment by zignig** [comment]
Post haste , upgrade.
